# process the test suites generated by Evosuite

import os
import re


def processFile(oldpath, newpath):
    oldFile = open(oldpath)
    newFile = open(newpath, 'w')
    records = oldFile.readlines()
    for line in records:
        if line.startswith('@RunWith(EvoRunner.class)'):
            continue
        elif line.find('_ESTest_scaffolding') != -1:
            p = re.compile('extends .*_ESTest_scaffolding ')
            newline = p.sub('', line)
            newFile.write(newline)
        else:
            newFile.write(line)
    oldFile.close()
    newFile.close()


def traverseRoot(rootDir):
    for root, dirs, files in os.walk(rootDir):
        for d in dirs:
            if d != 'evo':
                continue
            subrootDir = os.path.join(root, d)
            print subrootDir
            for subroot, subdirs, subfiles in os.walk(subrootDir):
                for f in subfiles:
                    if not f.endswith('_ESTest.java'):
                        continue
                    newroot = subroot.replace('\evo\\', '\myevo\\')
                    if not os.path.exists(newroot):
                        # print 'creating dir:', newroot
                        os.makedirs(newroot)
                    # print 'creating file:', os.path.join(newroot, f)
                    processFile(os.path.join(subroot, f), os.path.join(newroot, f))


if __name__ == '__main__':
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\pdfbox-2.0.0\pdfbox-2.0.0')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\\avro-1.8.1\\avro-1.8.1')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\\avro-1.6.0\\avro-1.6.0')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\\avro-1.3.0\\avro-1.3.0')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\ivy-2.3.0-2013.1\\ant-ivy')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\ivy-2.1.0-2009.10\\ant-ivy')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\ivy-2.2.0-2010.9\\ant-ivy')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\ivy-2.0.0-2009.1\\ant-ivy')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\pdfbox-2.0.4-2016.12\pdfbox-2.0.4')
    # traverseRoot('C:\Users\chenzhifei\Desktop\subjects\\pdfbox-1.8.4-2014.1\pdfbox-1.8.4')
    traverseRoot('C:\Users\chenzhifei\Desktop\subjects\\cxf-3.0.1\\apache-cxf-3.0.1')